### ISSUE TITLE
cas服务器拒绝单点登录

### ISSUE THREAD

**Issue by linzch3** [liangxj8/AutoScore#1]
使用login函数后返回的源码是酱的，貌似是cas服务器拒绝单点登录，能否指教一下如何解决这个问题？下面是提示的源码：

`<div id="msg" class="errors">
<h2>Non-secure Connection</h2>  
 <p>You are currently accessing CAS over a non-secure connection. Single Sign On WILL NOT WORK. In order to have single sign on work, you MUST log in over HTTPS.</p>
 </div>\n\n-->\n\n<div id="cookiesDisabled" class="errors" style="display:none;">
<h2>Browser cookies disabled</h2>
<p>Your browser does not accept cookies. Single Sign On WILL NOT WORK.</p>`

**Comment by liangxj8** [comment]
@linzch3 不知道你是直接跑的还是有做改动吗？因为 post 后获得一个这样的源码我好像在开发过程中有见过，但目前这个版本的代码在我的机器上测试过是没毛病的。出现这个问题的原因大概是是CAS要求HTTPS登录，而直接如果直接 `request.post` 的话CAS服务器收到的是HTTP请求或者是没有带 cookies 登录。

我当时的思路大概是这样：

- 关掉 Fiddler，因为他会改动端口导致报SSL错误。
- 将 `request.post` 改成 `requests.Session().post` 以启用 cookies 。

不知道能否帮助到你？

**Comment by linzch3** [comment]
@liangxj8 首先，谢谢你的回复ヽ(￣▽￣)و
我是直接跑你的代码中的login函数的。没有使用Fidder，也是调用`requests.Session().post`这个方法的。

下面是我的代码：

`
import requests
from bs4 import BeautifulSoup

session = requests.Session()
headers = {'User-Agent':'Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.98 Safari/537.36'}
url = "https://cas.sysu.edu.cn/cas/login;?service=http://finance.sysu.edu.cn:8800/CASLogin.aspx?url=http://finance.sysu.edu.cn:8800/Main.aspx"

def login():
#     if not username:
#         username = input('Please input your NetID: ')
#     if not password:
#         password = input('Please input your password: ')
    response = session.get(url, headers=headers, cookies=session.cookies)
    soup = BeautifulSoup(response.text, 'html.parser')
    lt = soup.find('input', {'name': 'lt'})['value']
    execution = soup.find('input', {'name': 'execution'})['value']
    payload = {
        'username': myNetID,
        'password': myPassWord,
        'lt': lt,
        'execution': execution,
        '_eventId': 'submit',
        'submit': '登录'
    }
    response = session.post(url, data=payload, cookies=session.cookies)
    return response
    
r = login()
r.text
`

**Comment by liangxj8** [comment]
@linzch3 仔细看一下你得到的 r.text 其实可以发现，里面一共有三个具有 `class="errors"` 属性的元素，其中两个的正文就是你提到的 `Non-secure Connection` 和 `Browser cookies disabled` 。但是， `Non-secure Connection` 这一块的代码是被注释掉的了，而 `Browser cookies disabled` 有一个属性 `style="display:none;"` ，也就是说，这两个如果是作为浏览器页面展示出来的话，是看不到的。

而第三个具有 `class="errors"` 属性的元素，他的正文内容是 `Invalid credentials.` 也就是说，你账号密码可能错了。我的 `cas_login(url, username, password)` 函数对这种情况是有进行处理的～

将你给出的 `r.text` 处理成HTML文件打开的效果如下：

![_20171026164335](https://user-images.githubusercontent.com/16259239/32043432-4fe0f956-ba6d-11e7-8e5c-ce1d6e029c29.png)

我使用你代码测试的结果：

![_20171026165116](https://user-images.githubusercontent.com/16259239/32043653-f5db9780-ba6d-11e7-945b-0c229541fc27.png)

**Comment by linzch3** [comment]
@liangxj8 哇呜，谢谢这么耐心而详细的debug!  感动

看了一下NetID，的确写错了，抱歉我的过。改了正确的密码后就可以运行了，赞ヽ(￣▽￣)و

之前运行代码时返回`Invalid credentials`时没多想，我以为是爬虫程序被识破了，真是不好意思了。

---

嘿嘿，这个问题解决了。我还想再问一下，你给的那个【微教务】系统的API好像失效了耶？

![image](https://user-images.githubusercontent.com/20380442/32053036-99fa2642-ba8c-11e7-98e9-c8873667414c.png)

**Comment by liangxj8** [comment]
@linzch3 密码输入错误后运行 `cas_login()` 的死循环是没毛病的，只要输入对了就会跳出了，不然的话只要输入错误就会退出登录进程了。然后【微教务】的API还能用，不过不能直接用，也不能直接登录CAS后用。因为微教务的CAS登录是跳转到教务系统再跳回来的，如果只是登录了CAS或者直接用的话都是会出现这个提示。另外，微教务登录超时而CAS没超时也会出现这种状况。所以我有带cookies登录以及 `main()` 里面会有注销重新登录。

**Comment by linzch3** [comment]
@liangxj8 好的，感觉很稳ヽ(￣▽￣)و 

那我再好好研究前辈的代码，今天真是非常感谢，致敬！
